name: Render UML Diagrams
on:
  push:
    branches:
      - main
    paths:
      - 'docs/UML/**/*.puml'
      - '.github/workflows/render_uml_diagrams.yml'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PlantUML
        run: sudo apt-get install plantuml
      - name: Generate PNGs
        run: |
          mkdir -p docs/UML/img
          for file in docs/UML/*.puml; do
            plantuml "$file" -tpng -o ./img
          done
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/UML/img/
          git commit -m "Auto-rendered UML diagrams" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/DTerian64/AIAgents.git HEAD:main
