name: Render UML Diagrams
on:
  push:
    branches:
      - main
    paths:
      - 'docs/UML/**/*.puml'
      - '.github/workflows/render_uml_diagrams.yml'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PlantUML
        run: sudo apt-get install plantuml
      - name: Generate PNGs
        run: |
          mkdir -p docs/UML/img
          for file in docs/UML/*.puml; do
            plantuml "$file" -tpng -o ./img
          done
      - name: Commit and Push UML Images
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add docs/UML/img/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-rendered UML diagrams"
            git push
          fi
